### PR TITLE
fix: correct pagetracker that use global reacti13n

### PR DESCRIPTION
**Pull request by umbobabo**

### CODE REVIEW

**Comment by keithamus** [comment]
Why do we need to do this?

**Comment by keithamus** [comment]
Rather than relying on implicit globals, you can call `getInstance()` on the root import - for example

```js
import Reacti13n from 'react-i13n';
// ...
const instance = Reacti13n.getInstance();
// ...
const instance.execute('pageview', pageInfo);
```

**Comment by fabiosantoscode** [comment]
```
import Reacti13n from 'react-i13n';
const instance = Reacti13n.getInstance();
```

Isn't this also just as much of an implicit global?

**Comment by keithamus** [comment]
@fabiosantoscode its out of our way because its behind the Reacti13n api, which means we dont have to harbour nastiness.

**Pull request merged**
