### PR TITLE
feat: provision

### PR DESCRIPTION
**Pull request by umbobabo**
BREAKING CHANGE:

The new provision require a new files structure

### CODE REVIEW

**Comment by keithamus** [comment]
Why is this a breaking change? It seems like this is not a breaking change.

**Comment by umbobabo** [comment]
Doesn't the structure, the './lib' folder, affect existing import?

**Comment by keithamus** [comment]
It does not because we have the package.json `main` and `style` fields which let the import semantics know that the files are in those locations. `require()` and `@import` will work exactly the same way.

**Comment by keithamus** [comment]
👍 great work

**Pull request merged**
